### ISSUE TITLE
Django 1.5 Compatibility for Configurable User

### ISSUE THREAD

**Issue by trent** [pinax/django-flag#7]
django-flag uses a direct foreign key to the User model. With the addition of configurable user model functionality in Django 1.5, a new setting 'AUTH_USER_MODEL' was introduced that should be used to reference the project's specific user model for relationships.

**Comment by pydanny** [comment]
:+1:

**Comment by blag** [comment]
This can also be closed now thanks to #10 getting merged. :smile:
